name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - hydra-core=1.3.2
  - matplotlib=3.9.2
  - pip=24.2
  - scikit-learn=1.5.2
  - jupyterlab=4.1.3
  - ipywidgets
  - pip:
      - mlflow==2.18.0
      - wandb==0.18.7
      - ydata_profiling==4.12.0
      - pandas==2.2.3
