name: nyc_airbnb_dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - hydra-core=1.3.2
  - matplotlib=3.9.2
  - pandas=2.2.3
  - jupyterlab=4.2.5
  - pip=24.2
  - pip:
      - mlflow==2.18.0
      - wandb==0.18.7