name: train_random_forest
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.0
  - hydra-core=1.3.2
  - matplotlib=3.9.2
  - pandas=2.2.3
  - pip=24.2
  - scikit-learn=1.5.2
  - pip:
      - mlflow==2.18.0
      - wandb==0.18.7
