name: download_file
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.0
  - pip=24.2
  - requests=2.32.3
  - pyarrow
  - pip:
      - mlflow==2.18.0
      - wandb==0.18.7
      - git+https://github.com/udacity/nd0821-c2-build-model-workflow-starter.git#egg=wandb-utils&subdirectory=components
